### ISSUE TITLE
ExecJS::RuntimeError, Cannot find module, Function.Module._resolveFileName, module.js

### ISSUE THREAD

**Issue by starrychloe** [sstephenson/execjs#117]
I'm getting the following error.

```
$ gem install 'execjs'
Successfully installed execjs-1.4.0
1 gem installed

$ irb
irb(main):001:0> require "execjs"
=> true
irb(main):002:0> ExecJS.eval "'red yellow blue'.split(' ')"
ExecJS::RuntimeError:
module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\tmp\execjs20130225-1276-12gom9m.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

        from /usr/lib/ruby/gems/1.9.1/gems/execjs-1.4.0/lib/execjs/external_runtime.rb:142:in `exec_runtime'
        from /usr/lib/ruby/gems/1.9.1/gems/execjs-1.4.0/lib/execjs/external_runtime.rb:28:in `block in exec'
        from /usr/lib/ruby/gems/1.9.1/gems/execjs-1.4.0/lib/execjs/external_runtime.rb:41:in `compile_to_tempfile'
        from /usr/lib/ruby/gems/1.9.1/gems/execjs-1.4.0/lib/execjs/external_runtime.rb:27:in `exec'
        from /usr/lib/ruby/gems/1.9.1/gems/execjs-1.4.0/lib/execjs/external_runtime.rb:19:in `eval'
        from /usr/lib/ruby/gems/1.9.1/gems/execjs-1.4.0/lib/execjs/runtime.rb:40:in `eval'
        from /usr/lib/ruby/gems/1.9.1/gems/execjs-1.4.0/lib/execjs/module.rb:23:in `eval'
        from (irb):2
        from /usr/bin/irb:12:in `<main>'
irb(main):003:0> quit

$ which node
/cygdrive/c/Program Files/nodejs/node

$ node -v
v0.8.20

$ uname -a
CYGWIN_NT-5.1 dumbopc 1.7.17(0.262/5/3) 2012-10-19 14:39 i686 Cygwin

$ ruby -v
ruby 1.9.3p385 (2013-02-06 revision 39114) [i386-cygwin]

```

I can't compile nodejs from source because it uses Windows assembly and requires a Microsoft ASM compiler, ml.exe. So I use the nodejs installation package for Windows.

**Comment by josh** [comment]
This repository has been deprecated and has moved to https://github.com/rails/execjs.
