### ISSUE TITLE
ExecJS doesn't find PATH variable

### ISSUE THREAD

**Issue by onnimonni** [sstephenson/execjs#141]
I tried my PATH and it works.

The error I'm getting while compiling coffeescript to js:
```bash
Output error:

/Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/execjs-2.0.2/lib/execjs/external_runtime.rb:124:in `locate_executable': undefined method `split' for nil:NilClass (NoMethodError)
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/execjs-2.0.2/lib/execjs/external_runtime.rb:160:in `block in which'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/execjs-2.0.2/lib/execjs/external_runtime.rb:158:in `each'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/execjs-2.0.2/lib/execjs/external_runtime.rb:158:in `find'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/execjs-2.0.2/lib/execjs/external_runtime.rb:158:in `which'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/execjs-2.0.2/lib/execjs/external_runtime.rb:147:in `locate_binary'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/execjs-2.0.2/lib/execjs/external_runtime.rb:113:in `binary'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/execjs-2.0.2/lib/execjs/external_runtime.rb:104:in `available?'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/execjs-2.0.2/lib/execjs/runtimes.rb:62:in `from_environment'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/execjs-2.0.2/lib/execjs/runtimes.rb:50:in `autodetect'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/execjs-2.0.2/lib/execjs.rb:5:in `<module:ExecJS>'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/execjs-2.0.2/lib/execjs.rb:4:in `<top (required)>'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/coffee-script-2.2.0/lib/coffee_script.rb:1:in `<top (required)>'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/coffee-script-2.2.0/lib/coffee-script.rb:1:in `<top (required)>'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Users/onnimonni/Projects/wordpress/wp-content/plugins/wordless/wordless/preprocessors/sprockets_preprocessor.rb:17:in `compile'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /Users/onnimonni/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Users/onnimonni/Projects/wordpress/wp-content/plugins/wordless/wordless/preprocessors/sprockets_preprocessor.rb:44:in `<main>'
```

The gems I'm using
```bash
$ rvm @wordless do gem list

*** LOCAL GEMS ***

activesupport (4.1.0.beta1)
atomic (1.1.14)
bigdecimal (1.2.0)
bundler (1.5.1)
bundler-unload (1.0.2)
celluloid (0.15.2)
chunky_png (1.2.9)
clipboard (1.0.5)
coffee-script (2.2.0)
coffee-script-source (1.6.3)
compass (1.0.0.alpha.18, 0.12.2)
compass-core (1.0.0.alpha.17)
compass-import-once (1.0.2)
dispel (0.0.4)
execjs (2.0.2)
executable-hooks (1.2.6)
ffi (1.9.3)
fssm (0.2.10)
gem-wrappers (1.2.4, 1.2.1)
hike (1.2.3)
i18n (0.6.9)
io-console (0.4.2)
json (1.7.7)
language_sniffer (1.0.2)
libv8 (3.16.14.3 x86_64-darwin-12)
listen (2.4.1, 1.1.6)
minitest (5.2.2, 4.3.2)
multi_json (1.8.4)
plist (3.1.0)
psych (2.0.0)
rack (1.5.2)
rake (0.9.6)
rb-fsevent (0.9.4)
rb-inotify (0.9.3)
rb-kqueue (0.2.0)
rdoc (4.0.0)
ref (1.0.5)
rubygems-bundler (1.4.2)
ruco (0.2.21)
rvm (1.11.3.8)
sass (3.3.0.rc.3)
sprockets (2.10.1)
test-unit (2.0.0.0)
textpow (1.3.1)
therubyracer (0.12.1)
thor (0.18.1)
thread_safe (0.1.3)
tilt (1.4.1)
timers (1.1.0)
tzinfo (1.1.0)
wordless (0.4.1)
wordpress_tools (0.0.2)
yui-compressor (0.12.0)
```

**Comment by josh** [comment]
This repository has been deprecated and has moved to https://github.com/rails/execjs.
