### ISSUE TITLE
runtimes.rb:  autodetect Could not find a JavaScript runtime

### ISSUE THREAD

**Issue by mnsanghvi** [sstephenson/execjs#154]
execjs: 2.2.1
ruby:  2.1.0
OS:  Debian/testing on PowerPC

I am trying to use Jekyll (http://www.jekylrb.com) and I get the following error when I do
anything with it:

```
% jekyll --version
/var/lib/gems/2.1.0/gems/execjs-2.2.1/lib/execjs/runtimes.rb:51:in `autodetect': Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
        from /var/lib/gems/2.1.0/gems/execjs-2.2.1/lib/execjs.rb:5:in `<module:ExecJS>'
        from /var/lib/gems/2.1.0/gems/execjs-2.2.1/lib/execjs.rb:4:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.1.0/gems/coffee-script-2.2.0/lib/coffee_script.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.1.0/gems/coffee-script-2.2.0/lib/coffee-script.rb:1:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.1.0/gems/jekyll-coffeescript-1.0.0/lib/jekyll-coffeescript.rb:2:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.1.0/gems/jekyll-2.1.0/lib/jekyll.rb:75:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.1.0/gems/jekyll-2.1.0/bin/jekyll:6:in `<top (required)>'
        from /usr/local/bin/jekyll:23:in `load'
        from /usr/local/bin/jekyll:23:in `<main>'

'''

I have Rhino and Spidermonkey installed.   I have also installed therubyrhino as per the documentation.

**Comment by welligton1993** [comment]
Add "gem 'therubyracer'" on Gemfile works for me...

**Comment by red-nova** [comment]
@welligton1993 adding that to the gemfile then using `bundle install` worked.

**Comment by welligton1993** [comment]
@red-nova  Exactly... Fist add "gem 'therubyracer' to Gemfile and after  execute bundle install

**Comment by vicmumo** [comment]
execjs: 2.2.1
ruby: 1.9.3-p551
OS: Ubuntu 14.04.01

Reproduced using this tutorial code https://github.com/gotealeaf/bootstrap-todo-app
Fixed adding 'therubyracer' to Gemfile as workaround worked for me

**Comment by josh** [comment]
This repository has been deprecated and has moved to https://github.com/rails/execjs.

**Comment by ganni** [comment]
installing therubyracer gem worked for me

**Comment by ghost** [comment]
nano Gemfile
add in the file : gem 'therubyracer'
bundle

Works great :+1:
