### ISSUE TITLE
Runtime Error with Rails

### ISSUE THREAD

**Issue by mattymess** [sstephenson/execjs#195]
This is a new computer and I don't experience this error on my old machine. Trying to hit a page in my app and getting the following runtime error.

I have node installed.

``` shell
ExecJS::RuntimeError - 
  (in /Users/mattmessinger/Work/fanbread/repos/toaster/vendor/assets/bower_components/angular-ui-bootstrap-bower/ui-bootstrap-tpls.js):
  execjs (2.5.0) lib/execjs/external_runtime.rb:226:in `exec_runtime_error'
  execjs (2.5.0) lib/execjs/external_runtime.rb:214:in `exec_runtime'
  execjs (2.5.0) lib/execjs/external_runtime.rb:39:in `exec'
  execjs (2.5.0) lib/execjs/external_runtime.rb:21:in `eval'
  execjs (2.5.0) lib/execjs/external_runtime.rb:46:in `call'
```

**Comment by akshaymohite** [comment]
I got similar issue while using `react-rails` gem 

``` Ruby
 react-rails (1.4.2)
      babel-transpiler (>= 0.7.0)
      coffee-script-source (~> 1.8)
      connection_pool
      execjs
      rails (>= 3.2)
      tilt
```

Error on `rails s`:

``` ruby
.
.
Error compiling asset application.js:
ExecJS::RuntimeError: SyntaxError: Invalid unicode escape in identifier: '\ufeff'
(in /Users/username/workspace/project/app/assets/javascripts/components/MyComponent.jsx)
```

**Comment by ynagorny** [comment]
I'm getting the same error on a new computer too. Have you been able to find out what's causing it?
